import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
// import styles from '../styles/Home.module.css'
import { useInView } from "react-intersection-observer";
import {motion,useAnimation} from "framer-motion";  
import { useEffect } from "react";



import Layout from "../components/Layout";
import CarouselList from "../components/CarouselList";
export default function Home() {

const {ref,inView}=   useInView();
const animation=useAnimation();

useEffect(()=>{
if(inView)
{
  animation.start({
    x:0,
    transition:{
      type:'spring',duration:1,bounce:0.3
    }
  });
}
if(!inView)
{
  animation.start({x:'-100vw'})
}

  console.log("Hook effect tutorial, InView ="+inView)
},[inView])


  return (
    <Layout
      mainTitle="My Home Page built with Next JS"
      footer={`Copyright ${new Date().getFullYear()}`}
    >
      <Head>
        <title>Swara Yoga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CarouselList></CarouselList>
      <div className="mt-3" >
        <div className="card  titlestrip ">
          <div className="card-header">
          <motion.div
            initial={{ x: -300, scale: 0.5 }}
            animate={{ x: 0, scale: 1 }}
            transition={{ duration: 2 }}
          >

<h3>Introduction to Swara Yoga</h3>
          </motion.div>


          </div>
          <div className="justifytext fs-5 p-3">
            We welcome visitors to this website to the fascinating and
            relatively unknown yoga – Swara Yoga. An ancient science of
            breathing. Contribute to extend your hand in our mission to spread
            this ancient science of breath.
          </div>


          <div className="justifytext fs-5 p-3 ">
            <p>
            The knowledge of Swara Yoga will surprise many that Yogis have discovered thousands of years back much more than what we know today about the breath. As per Swara Yoga, 
            Breath is the language of our Self and it has connection to all the movement of time (KALA) - persent past and future
          </p>
          </div>

<div ref={ref}>
          <motion.div className="justifytext fs-5 p-3 " animate={animation}>
            <h3>
            महेश्वरम् नमस्यकृत्यम् शैलजाम् गननायकम। गुरु च परमत्मानम् भजे संसार तारनम् ॥
            </h3>
          </motion.div>
          </div>

          <div className="justifytext fs-5 p-3">
            <p>
            Salutations to Maheshwara (Bhagwan Shiva), Godess Parvati the cosmic mother and Ganesha- destroyer of all obsticles and giver of wisdom, I bow to the guru who is verily the supreme consciousness (Paramatma) and capable of freeing from all the bondages of the mortal world. Sloka - 1 Shiva Swarodaya
          </p>
          </div>


          <div className="justifytext fs-5 p-3 zoom">
            <p>
            The word SWARA in Sanskrit, means sound or musical note; it also means the continuous flow of air through one nostril. And we all know that YOGA means union. So Swara Yoga is the science which is about the realization of cosmic consciousness, through the awareness or observation, then control or manipulation of the flow of breath in the nostrils.
          </p>
          </div>

          <div className="justifytext fs-5 p-3 zoom">
            <p>
            Swara yoga is an ancient tantric science which involves the systematic study of the breath flow through the nostrils (or swara) in relation to the prevailing phases of the moon, time of day and direction . Although we think of ‘pranayama’ when we think of techniques associated with the breath, in Swara yoga, it is the association of the breath in relation to the activities or phases or positions of the sun, moon, planets, seasons, time of day, with the physical and mental conditions of the individual and then taking the appropriate action according to these subtle relations. For example, knowing the moon phases and checking the flow of your nostrils before you get out of bed in the morning and letting the corresponding foot be the first to touch the floor and make the first step, is a simple practice that ensures success in everything that happens for that day. The first foot to touch the ground will get the prevailing ‘successful’ flow of energy from the cosmos.
          </p>
          </div>


          <div className="justifytext fs-5 p-3 zoom">
            <p>
            Swara yoga is an ancient science existing since before the Vedic period, over ten thousand years ago. It was a secret science, only available for the select few, specially kings and dedicated sadhaks. It was kept as a closed secret by the ancient sages and saints who had intuitively received this knowledge from the Divine.
          </p>
          </div>

          <div className="justifytext fs-5 p-3 zoom">
            <p>
            This ancient divine knowledge was available only for sadhaks, to those who had risen above the worldly and mundane affairs of life, those who had a spiritual attitude, and the dedication and devotion of a disciple, so that this precious knowledge was kept pure and it didn’t go into the wrong hands. It was used for yearly predictions and other divinations. It was used for those who had mental, physical, emotional, and spiritual problems so that they could get rid of their problems by using this divine knowledge of Swara Yoga. Also, it was useful for the Grahastha, the householder, in day to day matters. It was commonly used for general future predictions as well as in special cases such as making wars go according to the wishes of the king, or for having a divine child. It was used to choose an auspicious time, start special jobs, journeys, wars, building etc. and for creating harmony in world affairs, predicting the time of death, and to deal with planetary effects, astral forces and negative effects of planets of the zodiac and the constellations.
          </p>
          </div>

          <div className="justifytext fs-5 p-3 zoom">
            <p>
            Through the knowledge of swara yoga one can become free from all kinds of negative influences of one’s destiny and can achieve heightened awareness. The swara yoga practices related to breath were used to understand the governing forces of life, to understand the nature of the universe and effects of the elements on body and mind by observing the different patterns of breath. Further, it was used to go beyond the limitations of the mind. Swara yoga is a tantric science coming from the Agama Shastras and from Shaiva Tantra, where Lord Siva is the guru and Shakti is the disciple She asks questions about nature and the governing forces of the universe. Lord Siva gives this precious knowledge of swara yoga to Shakti. Other tantric traditions also existed such as Surya tantra, Ganapatya tantra and Vaishnava tantra. Today only two tantric techniques are commonly available, Saiva and Shakta tantra.
          </p>
          </div>

          <div className="justifytext fs-5 p-3 zoom">
            <p>
            The fascinating thing about Swara yoga is that just by being aware of the swara (dominant nostril) in relation to the environment, you can manipulate the results of what you are about to do. In other words, you can find out which is going to be the successful route and then follow it. It can be as simple as checking your nostrils before setting out of the house, noting the direction you wish to go in and then choosing the appropriate foot with which you will make your first step, to ensure success and positive outcomes for everything that follows thereafter.
          </p>
          </div>



          



        </div>
      </div>
    </Layout>
  );
}
